---
- name: Has gradle config dir
  tags: gradle
  file:
    path: ~/.gradle
    state: directory

- name: Has init script
  tags: gradle
  template   :
      src    : templates/init.gradle
      dest   : ~/.gradle/init.gradle
      backup : yes

- name: Has logging config
  tags: gradle
  template   :
      src    : templates/logback.groovy
      dest   : ~/.gradle/logback.groovy
      backup : yes
