---
# tasks file for docker
- name: Has dnf plugins installed installed
  become: true
  tags: [docker,system]
  package:
    name: dnf-plugins-core

- name: Has configured repos
  become: true
  tags: [docker,system] 
  command: "dnf config-manager \ --add-repo \ https://download.docker.com/linux/fedora/docker-ce.repo"

- name: Has configured repos
  become: true
  tags: [docker,system]
  command: "dnf makecache"

- name: Has docker-ce
  become: true
  tags: [docker,system]
  package:
    name: docker-ce
