---
- name: Has clipster clipboard manager
  tags: clipster
  git    :
    repo : https://github.com/mrichar1/clipster.git
    dest : ~/Coding/soft/clipster

- name: Has clipster dependencies
  become: true
  tags: clipster, system
  package  :
    name   : libwnck3
    state  : present

- name: Has clipster config dir
  tags: clipster
  file     :
      path : ~/.config/clipster
      state: directory

- name: Has default clipster config
  tags: clipster
  blockinfile :
    dest      : ~/.config/clipster/clipster.ini
    create    : yes
    marker    : "# {mark} clipster config"
    content   : |
        [clipster]
        data_dir = $XDG_DATA_HOME
        default_selection = PRIMARY
        active_selections = PRIMARY,CLIPBOARD
        sync_selections = yes
        history_file = %(data_dir)s/history
        history_size = 200
        history_update_interval = 60
        write_on_change = no
        socket_file = %(data_dir)s/clipster_sock
        pid_file = %(data_dir)s/clipster.pid
        max_input = 50000
        row_height = 100
        duplicates = no
        smart_update = 1
        extract_uris = yes
        extract_emails = yes
        extract_patterns = no
        filter_classes = ""
