---
- name: Has ranger
  become: true
  tags: ranger, system
  package:
    name: ranger
    state: present

- name: Has ; as leader key
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    create: yes
    line: "unmap ;"
    state: present

- name: Has rg function in bashrc for opening ranger
  tags: ranger
  blockinfile:
    dest: "{{ bash_config_dir }}/ranger"
    marker: "# {mark} ff function for opening ranger (ansible managed)"
    create: yes
    content: |
        rg() {
            if [ -z "$RANGER_LEVEL" ]
            then
                clear
                ranger
            else
                exit
            fi
        }

- name: Has hotkey for Go to Projects
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    create: yes
    line: "map ;jp      cd ~/Coding/projects"
    state: present
    regexp: "map ;jp.*"

- name: Has hotkey for Go to Sources
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    create: yes
    line: "map ;js      cd ~/Coding/sources"
    state: present

- name: Has hotkey for Go to Home
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    create: yes
    line: "map ;jh      cd ~/"
    state: present

- name: Has hotkey for Go to Downloads
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map ;jd      cd ~/Downloads"
    state: present
    regexp: "map ;jd.*"

- name: Has hotkey for shell
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map s    shell $SHELL"
    state: present

- name: Has hotkey for shell
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "map S    console shell%space"
    state: present

- name: Has colorscheme setted
  tags: ranger
  lineinfile:
    dest: ~/.config/ranger/rc.conf
    line: "set colorscheme snow"
    state: present
    regexp: "set colorscheme.*"

- name: Has .bashrc sourced
  tags: ranger
  lineinfile:
    dest: ~/.bashrc
    create: yes
    line: "source {{ bash_config_dir }}/ranger"
