---
- name: Has hotkeys settings
  tags: vim
  blockinfile :
    create    : yes
    dest      : "{{ vim_config_dir }}/hotkeys"
    marker    : '"{mark} hotkeys settings'
    content   : | 
        map <silent> <leader>m :Build<cr>
        map <silent> <leader>qo :copen<cr>
        map <silent> <leader>qc :cclose<cr>
        nnoremap <silent> <leader>j :bp<cr>
        nnoremap <silent> <leader>k :bn<cr>
        nnoremap <leader>y "+y"
        vnoremap <leader>y "+y"

- name: Has hotkeys  file sourced into .vimrc
  tags: vim
  lineinfile  :
    line      : "source {{ vim_config_dir }}/hotkeys"
    dest      : ~/.vimrc
    create    : yes
    state     : present
    regexp    : "source {{ vim_config_dir }}/hotkeys"
