---
- name: Has directory for vim
  tags: vim
  file:
    path: "{{ vim_dir }}"
    state: directory

- name: Has config directory
  tags: vim
  file:
    path: "{{ vim_config_dir }}"
    state: directory

- name: Has gcc for vim
  tags: vim, system
  become: true
  package:
    name: gcc

- name: Has python-devel for vim
  tags: vim, system
  become: true
  package:
    name: python-devel
  notify: build vim from sources

- name: Has python3-devel for vim
  tags: vim, system
  become: true
  package:
    name: python3-devel
  notify: build vim from sources

- name: Has automake for vim
  tags: vim, system
  become: true
  package:
    name: automake

- name: Has ncurses for vim
  tags: vim, system
  become: true
  package:
    name: ncurses

- name: Has ncurses-devel for vim
  tags: vim, system
  become: true
  package:
    name: ncurses-devel

- name: Has vim sources
  tags: vim, system
  become: true
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ vim_dir }}/sources"
  notify: build vim from sources

- name: Vim used as system default editor
  tags: vim
  lineinfile  :
      dest    : "{{ bash_config_dir }}/vim"
      line    : export EDITOR=vim
      state   : present
      create  : yes

- name: trigger rebuild vim
  tags: rebuild
  command: "echo test"
  notify: build vim from sources
