---
- name: Has python dev headers
  tags: ansible-hacking, system
  become: true
  package:
    name: python-devel
    state: present

- name: Has git
  tags: ansible-hacking, system
  become: true
  package:
    name: git
    state: present

- name: Has pyyaml installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: pyyaml
    executable: pip2

- name: Has jinja2 installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: jinja2
    executable: pip2

- name: Has nose installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: nose
    executable: pip2

- name: Has passlib installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: passlib
    executable: pip2

- name: Has pycrypto installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: pycrypto
    executable: pip2

- name: Has epdb installed
  tags: ansible-hacking, system
  become: true
  pip:
    name: epdb 
    executable: pip2

- name: Has cloned ansible sources with ansible-hacking
  tags: ansible-hacking
  git:
    accept_hostkey: yes
    repo: https://github.com/ansible/ansible.git
    dest: ~/Coding/soft/ansible

- name: Has alias for ansible test-module
  tags: ansible-hacking
  blockinfile:
    marker: "# {mark} ansible test-module alias (ansible managed)"
    dest: ~/.bashrc
    content: |
        test() {
            source ~/Coding/soft/ansible/hacking/env-setup
            ~/Coding/soft/ansible/hacking/test-module -m $1 -a $2
        }
