- name: Has bash config dir
  tags: bash
  file:
    path:  "{{ bash_config_dir }}"
    state: directory

- name: Has configs for interactive session
  tags: bash
  copy   :
      src:    templates/interactive.d
      dest:   "{{ bash_config_dir }}/"
      
- name: Has configs for interactive and non interactive
  tags: bash
  copy   :
      src:    templates/common.d
      dest:   "{{ bash_config_dir }}/"

- name: Has bash main config
  tags: bash
  copy   :
      src:    templates/config.bash
      dest:   "{{ bash_config_dir }}/config.bash"
