- name: Has alias for ansible-playbook
  tags: ansible
  lineinfile:
    line: "alias ap=ansible-playbook" 
    dest: "{{ bash_config_dir }}/ansible"
    create: yes

- name: Has setting for using custom config
  tags: ansible
  lineinfile:
    line: "export ANSIBLE_CONFIG='/home/stcarolas/.ansible/ansible.cfg'"
    dest: "{{ bash_config_dir }}/ansible"
    create: yes

- name: Has .bashrc sourced
  tags: ansible 
  lineinfile:
    dest: ~/.bashrc
    create: yes
    line: "source {{ bash_config_dir }}/ansible"
