---
# tasks file for zsh
- name: Has zsh
  tags: [zsh,system]
  become: true
  package:
      name: zsh
      state: present

#- name: Has zplug installed
  #tags: zsh
  #shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh"

#- name: Has zplug installed
  #tags: zsh
  #become: true
  #package:
      #name: xclip
      #state: present
 
- name: Has antigen installed
  tags: zsh
  shell: "curl -L git.io/antigen > ~/.config/antigen.zsh"

- name: Has zsh as default
  tags: zsh
  shell: "chsh -s $(which zsh)"

- name: Has zsh config
  tags: zsh
  copy:
    src: templates/config
    dest: ~/.zshrc
    force: yes
