---
- name: Has git cli
  tags: git, system
  become: true
  package:
    name: libselinux-python

- name: Has git cli
  tags: git, system
  become: true
  package:
    name: git

- name: Has bash dir
  tags: git
  file   :
    dest : "{{ bash_config_dir }}"
    state: directory

- name: Has git config dir
  tags: git
  file   :
    dest : "~/.config/git"
    state: directory

- name: Has config script
  tags: git
  template   :
      src    : templates/ignore
      dest   : "~/.config/git/ignore"
      backup : yes

- name: Has config for git
  tags: bash
  blockinfile:
    marker: "# {mark} git aliases (ansible managed)"
    dest: "{{ bash_config_dir }}/git"
    create: yes
    content: |
        alias gs='git status'
        alias gc='git commit'
        alias ga='git add'
        alias gp='git pull'
        alias gpull='git pull'
        alias gP='git push'
        alias gpush='git push'
        alias gf='git fetch'
        alias gd='git diff'
