---
- name: build vim from sources
  become: true
  tags: [ vim, system ]
  shell: "cd {{ vim_dir }}/sources 
            && ./configure  
                --enable-pythoninterp=yes 
                --with-python-config-dir=/usr/lib64/python2.7/config
                --with-python3-config-dir=/usr/lib64/python3.5/config-3.5m
                --enable-python3interp=yes  
            && make 
            && make install "

- name: install plugins
  tags: vim
  command: 'vim -c "exec Install()"'

- name: install gtags plugin
  tags: vim
  shell: cp /usr/share/gtags/gtags.vim ~/.vim/plugin/gtags.vim
